### ISSUE TITLE
Blank page after second request

### ISSUE THREAD

**Issue by Dropsik** [patrickdappollonio/http-server#34]
I put simple page https://github.com/rosgas/responsive-timeline and after few request I get blank page:
Logs from docker:
`http-ipsc-http-ipsc-1  | 2023/04/04 10:10:47 GET "/season2023/" -- HTTP/1.1 200 OK (served in 665.775µs; 4024 bytes)
http-ipsc-http-ipsc-1  | 2023/04/04 10:12:52 GET "/season2023/" -- HTTP/1.1 200 OK (served in 322.191µs; 0 bytes)`
First request page display correctly, second request 0 bytes send :(

at the same time, file index works - so it's a problem only with this page

**Comment by patrickdappollonio** [comment]
Hey @Dropsik!

Thanks a lot for opening this issue! Indeed you have found a golden nugget! 😅

The issue was due to this line being missing: https://github.com/patrickdappollonio/http-server/blob/dac84bb94dd7036608ea872a681199a717dd31ce/internal/mw/etag.go#L64

Basically, I added Etag handling, but Go has its own as well. I was not "trusting" the Go handling side by passing it back to you, and returning the default status code instead (your `0 bytes` written gave it away).

I'm about to merge the fix, and I'll circle back with you here to see if you can test the new version.

**Comment by patrickdappollonio** [comment]
Reopening to wait for feedback.

I also added a `--disable-etag` flag that you can set in case you want to completely disable my handling of ETags and use the partial one that comes with the language.

If you can please try the version 2.1.2, that would be awesome!

**Comment by Dropsik** [comment]
After clear browser cache, seems to be working.
in logs
`HTTP/1.1 304 Not Modified (served in 174.433µs; 0 bytes)`

**Comment by patrickdappollonio** [comment]
Awesome! Thanks a lot for confirming! I'll close this now. Feel free to open a new issue if you find any problem!
